.github/ISSUE_TEMPLATE/performance.md
.github/PULL_REQUEST_TEMPLATE.md
.husky/.commit-template
.husky/prepare-commit-msg
package-lock.json
package.json

- Add a new issue template for github for performance matter
- Add a git commit template

23 performance issue template

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

* Ref: #32
Reviewer:
@blueur @guilbep

chore(contributing): work on code review process

---

.gitignore
README.md
frontend/package-lock.json
frontend/package.json
frontend/src/components/LoginComponent.vue
frontend/src/components/commons/UserManager.vue
frontend/src/components/green_house_gaz/NewSurveyDialog.vue
frontend/src/components/green_house_gaz/SurveysList.vue
frontend/src/env.d.ts
frontend/src/plugins/user.ts
frontend/src/store/GhgModule.ts
frontend/src/store/UserModule.ts

**What kind of change does this PR introduce?** (check at least one)
**Does this PR introduce a breaking change?** (check one)
If yes, please describe the impact and communicate accordingly:
- When loading the app (in a new tab) new browser session we stay logged-in (we didn't load the information from the sessionStorage.token
- When login out of the app while logged in as a unhcr user, we really log out (cf issue #38 )
**The PR fulfills these requirements:**
**Other information:**
* Ref: #38 #39 
@blueur @guilbep

fix(rights): better rights with azure #38, #39

---

frontend/src/components/green_house_gaz/Results.vue

Closes #58
Transform to uppercase Wash into WASH
- Ref: #58

fix(ghg): transform to uppercase Wash into WASH

---

frontend/src/components/green_house_gaz/Results.vue
frontend/src/components/green_house_gaz/energy/EndlineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/Facilities.vue

Closes #53
Add (endline - baseline) absolute value after the percentage in change of emission in tCO2/year
- Ref: #53

feat(ghg): add absolute change in emission for results and facilities

---

frontend/src/components/AppList.vue
frontend/src/components/green_house_gaz/Results.vue
frontend/src/components/green_house_gaz/SurveyItemTitle.vue
frontend/src/components/green_house_gaz/infoTooltipText.ts
frontend/src/utils/apps.ts
frontend/src/views/AboutView.vue

Closes #52
Add information about the ghg app to information tooltip and about pages
- Ref: #52

feat(ghg): add estimation clause to results, facilities and about page

---

frontend/src/components/green_house_gaz/energy/BaselineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/EndlineFacilitiesTable.vue

fix(ghg): replace Renewable (kWh) by Renewables (kW)

---

frontend/src/components/green_house_gaz/Info.vue
frontend/src/components/green_house_gaz/NewSurveyDialog.vue

We disable the change of the site name, so to avoid conflicts with aggregate and modification
- Ref: #48

48 bug create new assessment with unhcr account

---

couchdb/bootstrap/ghg_reference/ghg_reference.json
frontend/src/components/green_house_gaz/energy/BaselineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/DieselGenerators.vue
frontend/src/components/green_house_gaz/energy/Facilities.vue
frontend/src/components/green_house_gaz/energy/Facility.ts
frontend/src/components/green_house_gaz/energy/FacilityDialog.vue
frontend/src/components/green_house_gaz/energy/InterventionDialog.vue
frontend/src/components/green_house_gaz/energy/computeCO2cost.ts
frontend/src/components/reference_data/GHG.vue
frontend/src/store/GhgInterface.ts

Add diesel estimation with KW and number of hours
- Ref: #106

106 feature facilities add diesel estimation 106

---

frontend/src/components/green_house_gaz/energy/Facilities.vue
frontend/src/store/GhgInterface.ts

Add a yellow/ warning vuetify box when kwh is not the same for baseline and endline
- Ref: #105

feat(ghg): add warning for facilities screen when kwh differs #105

---

frontend/src/components/energy/EnergyChart.vue
frontend/src/components/energy/EnergyCookingResult.vue
frontend/src/components/energy/EnergyKeyIndicator.vue
frontend/src/components/green_house_gaz/Results.vue
frontend/src/components/green_house_gaz/energy/BaselineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/EndlineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/Facilities.vue
frontend/src/components/green_house_gaz/wash/Trucking.vue
frontend/src/plugins/filters.ts
frontend/src/views/shelter_sustainability/ShelterSustainabilityCompare.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step3BillOfQuantities.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step9ScoreCard.vue

Easier to override default args of custom formatter + add a way to dynamically provide a suffix
- Ref: #156

fix(filters): rewrite formatNumber filter

---

frontend/src/components/green_house_gaz/energy/DieselGeneratorWithoutLitres.vue
frontend/src/components/green_house_gaz/energy/computeCO2cost.ts

166 add info hovers for diesel generator

---

frontend/src/components/green_house_gaz/energy/BaselineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/DieselGeneratorWithoutLitres.vue
frontend/src/components/green_house_gaz/energy/EndlineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/Facilities.vue
frontend/src/components/green_house_gaz/energy/Facility.ts
frontend/src/components/green_house_gaz/energy/FacilityDialog.vue
frontend/src/components/green_house_gaz/energy/InterventionDialog.vue
frontend/src/components/green_house_gaz/energy/computeCO2cost.ts
frontend/src/components/green_house_gaz/generic/EndlineCard.vue
frontend/src/store/GhgInterface.vue

closes #171 and #170
- Ref: #171 #70

fix(171): add litresPower and other changes

---

couchdb/bootstrap/ghg_reference/ghg_reference.json
couchdb/rawdata/Makefile
couchdb/rawdata/data_converter_whole.py
couchdb/rawdata/ghg_reference.csv
frontend/src/components/green_house_gaz/energy/BaselineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/Cooking.vue
frontend/src/components/green_house_gaz/energy/EndlineFacilitiesTable.vue
frontend/src/components/green_house_gaz/energy/Facilities.vue
frontend/src/components/green_house_gaz/energy/FacilityDialog.vue
frontend/src/components/green_house_gaz/energy/InterventionDialog.vue
frontend/src/components/green_house_gaz/energy/computeCO2cost.ts
frontend/src/components/green_house_gaz/wash/Trucking.vue

chore(database): update ghg_reference

---

frontend/src/components/green_house_gaz/energy/computeCO2cost.ts

fix(ghg): set year duration to 365.25 days

---

README.md
couchdb/bootstrap/_users/samuel.json

chore(database): add and document new user

---

frontend/src/components/green_house_gaz/wash/Trucking.vue

feat(ghg): fix WASH Trucking titles

---

couchdb-setup/bootstrap/ghg/_design/project/validate_doc_update.js
couchdb-setup/bootstrap/shelters/_design/shelter/validate_doc_update.js
frontend/src/App.vue
frontend/src/components/LoginComponent.vue
frontend/src/plugins/user.ts
frontend/src/store/ShelterModule.ts
frontend/src/store/UserModule.ts
frontend/src/utils/couchdb.ts

For jwt and couchdb users the authentication process had some holes.
- the jwt token was not check against its 'exp' field (a.k.a expiration date)
- the auth token from couchdb was not set
- We check the authentication every five minutes
- Ref: #221

feat(authentication): better authentication logic

---

.gitignore
Makefile

Take care of the backup question #136 
If no need to backup log files or CouchDB config files, then this is ready.
- #136

fix #136 feat(backup): remove unnecessary commands

---

frontend/src/App.vue

Closes #264
Add documentation for ghg as pdf
- Ref: #264

feat(ghg): add documentation as pdf in iframe

---

frontend/src/components/green_house_gaz/energy/Pumping.vue
frontend/src/components/green_house_gaz/infoTooltipText.ts

New module for wash pumping / same as facilities but different naming
- Ref: #210

feat(ghg): add wash water pumping module like facility

---

frontend/src/components/shelter_sustainability/billOfQuantities/ItemDialog.vue

Place 'Other' at the end of the v-select list of items.
- Ref: #301

feat(shelter): add Other at the bottom of the form: fixes #301

---

frontend/src/App.vue
frontend/src/mixins/update.js
frontend/src/registerServiceWorker.ts
frontend/tsconfig.json
frontend/vue.config.js

- See issue #319 for more information
- Instead of forcing the reload on the user side, we ask for a user action
- Ref: #319

Feat/319 send update notification on new version fix #319

---

frontend/src/components/green_house_gaz/generic/BaselineEndlineWrapper.vue
frontend/src/components/green_house_gaz/generic/ComputeGenericFormSurveyMixin.vue
frontend/src/components/green_house_gaz/generic/InstanceTable.vue
frontend/src/components/green_house_gaz/generic/SurveyItemDialog.vue
frontend/src/components/green_house_gaz/generic/surveyTableHeader.ts
frontend/src/store/GhgInterface.vue

Ghg feedback april/feat/325 turn onoff each row in endline

---

frontend/src/components/green_house_gaz/generic/EndlineCard.vue
frontend/src/components/green_house_gaz/generic/WarningMessageAlert.vue
frontend/src/components/green_house_gaz/generic/WarningSurveyDialog.vue

Add popup to confirm the user had the info
- Ref: #350

feat(ghg): add warning popup on change with bad diff

---

docker-compose.yml
uploadFASTAPI/unhcr_tss/config.py
uploadFASTAPI/unhcr_tss/routers/files.py
uploadFASTAPI/unhcr_tss/utils/s3client.py

The S3 endpoint URL `https://s3.epfl.ch` was hard coded. Make sure it comes from the environment variables. it will allow testing using a local S3 over HTTP service (such as minio).

feat: finalize s3 endpoint url configuration

---

couchdb-setup/bootstrap/shelters/_design/shelter/views/list/map.js
frontend/src/App.vue
frontend/src/components/shelter_sustainability/FormGroup.vue
frontend/src/store/ShelterInterface.ts
frontend/src/store/ShelterModule.ts
frontend/src/store/ShelterModuleUtils.ts
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step10ReportCard.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step1ProjectInformation.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step2Geometry.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step5EnvironmentalImpact.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step9ScoreCard.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityList.vue

feat(shelter): add public/private view for projects

---

frontend/src/components/green_house_gaz/generic/InstanceTable.vue
frontend/src/components/green_house_gaz/generic/SurveyItemDialog.vue
frontend/src/components/green_house_gaz/generic/surveyTableHeader.ts
frontend/src/components/green_house_gaz/infoTooltipText.ts
frontend/src/components/green_house_gaz/materials/DomesticSolidWaste.ts

fix(ghg): solid waste module ready with dynamic sub process

---

couchdb-setup/rawdata/ghg_default_value.csv
frontend/src/assets/references/ghg_default_value.json
frontend/src/components/green_house_gaz/energy/Cooking.ts
frontend/src/components/green_house_gaz/energy/CookstoveTech.ts
frontend/src/components/green_house_gaz/energy/Lighting.ts
frontend/src/components/green_house_gaz/fuelTypes.ts
frontend/src/components/green_house_gaz/generic/SurveyItemDialog.vue
frontend/src/components/green_house_gaz/generic/surveyTableHeader.ts
frontend/src/components/green_house_gaz/wash/DomesticSolidWaste.ts
frontend/src/components/reference_data/DefaultValues.vue
frontend/src/components/reference_data/EmissionFactors.vue

Move all the default values hard coded into the code in a reference file generated via a csv extracted from a shared excel file
- Ref: #608

fix(ghg): add all the other default values to the reference csv #608

---

frontend/src/components/AppList.vue
frontend/src/components/LoginComponent.vue
frontend/src/plugins/user.ts
frontend/src/store/UserModule.ts
frontend/vue.config.js

- remove oauth verification for custom code (no need anymore, msal browser replace it)

feat(frontend): no more weird oauth code verification

---

frontend/src/store/ShelterModuleUtils.ts
frontend/src/views/shelter_sustainability/ShelterSustainabilityItem/Step7Habitability.vue

Due to legacy schema, some na field where not set to undefined
- Ref: #652

fix(shelter): reset non applicable field of computed field

---

frontend/src/store/GhgModule.ts
frontend/src/store/ShelterModule.ts
frontend/src/utils/couchdb.ts
frontend/src/views/green_house_gaz/GreenHouseGazDashboard.vue
frontend/src/views/green_house_gaz/GreenHouseGazItem/SurveysItem.vue
frontend/src/views/shelter_sustainability/ShelterSustainabilityList.vue

Save to localDB when guest mode

feat(frontend): guest can store to local storage
